version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_application.sh
  ApplicationStop:
    - location: scripts/stop_application.sh