version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fastapi-app
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: root
      environment:
        variables:
          PROJECT_NAME: $PROJECT_NAME
          ENVIRONMENT: $ENVIRONMENT
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          ECR_REPOSITORY_URL: $ECR_REPOSITORY_URL
          ECR_REPOSITORY_NAME: $ECR_REPOSITORY_NAME
  ApplicationStop:
    - location: scripts/stop_application.sh