services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app-network

  fastapi:
    build:
      dockerfile: Dockerfile
    expose:
      - "3000"
    command: uvicorn main:app --host=0.0.0.0 --port=3000 --workers=4
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge